exports.gigData = [
	{
		date: "19-03-2022",
		venue_id: 30,
		spotify: "https://open.spotify.com/artist/6M6XXCcO5gI68XpIlrUL3Z",
		end: "22:00",
		description:
			"Young T & Bugsey are a British hip hop duo from Nottingham, consisting of rappers Ra'chard Young T Tucker and Doyin Bugsey Julius.",
		id: "63",
		price: 15,
		genre: "Hip Hop",
		bandName: "Young T & Bugsey",
		start: "20:15",
		big_url: "",
		small_url: "",
	},
	{
		date: "25-03-2022",
		venue_id: 1,
		spotify: "https://open.spotify.com/artist/0W2ZH8knJiOzH0ZwXnsgox",
		end: "22:30",
		price: 30,
		description:
			"The Four Owls, or simply The Owls is a British hip hop group formed in 2011. The group is signed to English label High Focus Records and is composed entirely of previously established High Focus members under bird-themed aliases: Fliptrix, Verb T, BVA, and Leaf Dog.",
		id: "64",
		genre: "Hip Hop",
		start: "20:15",
		bandName: "The Four Owls",
	},
	{
		date: "18-03-2022",
		venue_id: 4,
		spotify: "https://open.spotify.com/artist/1N2FgBLehaq77UEdJhCt7f",
		end: "01:00",
		price: 10.5,
		description:
			"Saint Etienne are an English band from London, formed in 1990. The band consists of Sarah Cracknell, Bob Stanley and Pete Wiggs. They became associated with the UK's indie dance scene in the 1990s, beginning with the release of their debut album Foxbase Alpha in 1991.",
		id: "36",
		genre: "Electronic",
		start: "21:00",
		bandName: "Saint Etienne",
	},
	{
		date: "20-03-2022",
		venue_id: 16,
		spotify: "https://open.spotify.com/artist/1Dvfqq39HxvCJ3GvfeIFuT",
		end: "23:45",
		price: 23,
		description:
			"Mastodon is an American heavy metal band from Atlanta, Georgia, formed in 2000. The group is composed of Troy Sanders, Brent Hinds, Bill Kelliher, and Brann Dailor. Mastodon has released eight studio albums, as well as a number of other releases.",
		id: "49",
		genre: "Rock",
		start: "21:30",
		bandName: "Mastodon",
	},
	{
		date: "18-03-2022",
		venue_id: 1,
		spotify: "https://open.spotify.com/artist/2jYMYP2SVifgmzNRQJx3SJ",
		end: "21:00",
		price: 28,
		description:
			"Modeselektor is a German electronic music duo consisting of Gernot Bronsert and Sebastian Szary.",
		id: "33",
		genre: "Electronic",
		start: "18:30",
		bandName: "Modeselektor",
	},
	{
		date: "11-03-2022",
		venue_id: 15,
		spotify: "https://open.spotify.com/artist/1h6Cn3P4NGzXbaXidqURXs",
		end: "20:00",
		price: 20,
		description:
			"Swedish House Mafia is a Swedish house music supergroup consisting of Axwell, Steve Angello and Sebastian Ingrosso.",
		id: "22",
		genre: "Electronic",
		start: "22:30",
		bandName: "Swedish House Mafia",
	},
	{
		date: "12-03-2022",
		venue_id: 19,
		spotify: "https://open.spotify.com/artist/4wLIbcoqmqI4WZHDiBxeCB",
		end: "20:45",
		description:
			"Sleater-Kinney is an American rock band that formed in Olympia, Washington, in 1994. The band's current lineup features Corin Tucker and Carrie Brownstein, following the departure of longtime member Janet Weiss in 2019.",
		id: "18",
		price: 24.99,
		genre: "Rock",
		bandName: "Sleater-Kinney",
		start: "18:45",
	},
	{
		date: "18-03-2022",
		venue_id: 17,
		spotify: "https://open.spotify.com/artist/6XYvaoDGE0VmRt83Jss9Sn",
		end: "23:45",
		price: 23,
		description:
			"King Gizzard & the Lizard Wizard are an Australian rock band formed in 2010 in Melbourne, Victoria. The band consists of Stu Mackenzie, Ambrose Kenny-Smith, Cook Craig, Joey Walker, Lucas Harwood, and Michael Cavanagh.",
		id: "50",
		genre: "Rock",
		start: "21:30",
		bandName: "King Gizzard & the Lizard Wizard",
	},
	{
		date: "12-03-2022",
		venue_id: 21,
		spotify: "https://open.spotify.com/artist/1yAwtBaoHLEDWAnWR87hBT",
		end: "21:45",
		price: 15,
		description:
			"Modest Mouse is an American rock band formed in 1992 in Issaquah, Washington, and currently based in Portland, Oregon. The founding members are lead singer/guitarist Isaac Brock, drummer Jeremiah Green, and bassist Eric Judy.",
		id: "16",
		genre: "Rock",
		start: "19:00",
		bandName: "Modest Mouse",
	},
	{
		date: "19-03-2022",
		venue_id: 8,
		spotify: "https://open.spotify.com/album/09du8TXw7b4n3qPUEhJ2tS",
		end: "22:30",
		price: 9,
		description:
			"The Grid are an English electronic dance group, consisting of David Ball and Richard Norris, with guest contributions from other musicians. They are best known for the hits Swamp Thing, Texas Cowboys, Crystal Clear, Rollercoaster and Floatation.",
		id: "40",
		genre: "Electronic",
		start: "19:30",
		bandName: "The Grid",
	},
	{
		date: "12-03-2022",
		venue_id: 3,
		spotify: "https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5",
		end: "23:30",
		description:
			"The Red Hot Chili Peppers are an American rock band formed in Los Angeles in 1983. Their music incorporates elements of alternative rock, funk, punk rock and psychedelic rock. The band consists of co-founders Anthony Kiedis (lead vocals) and Flea (bass), as well as drummer Chad Smith, and guitarist John Frusciante. With over 100 million records sold worldwide, the Red Hot Chili Peppers are one of the best-selling bands of all time.",
		id: "2",
		price: 55,
		genre: "Rock",
		bandName: "Red Hot Chili Peppers",
		start: "22:00",
	},
	{
		date: "13-03-2022",
		venue_id: 23,
		spotify: "https://open.spotify.com/artist/4MzJMcHQBl9SIYSjwWn8QW",
		end: "21:45",
		price: 18,
		description:
			"Spiritbox is a Canadian heavy metal band from Victoria, British Columbia. Husband and wife duo guitarist Mike Stringer and vocalist Courtney LaPlante established Spiritbox in 2017. The band's full lineup comprises LaPlante and Stringer, bassist Bill Crook, and drummer Zev Rose.",
		id: "13",
		genre: "Metal",
		start: "19:00",
		bandName: "Spiritbox",
	},
	{
		date: "18-03-2022",
		venue_id: 21,
		spotify: "https://open.spotify.com/artist/5WSlKTn8XCAH31eAVaJ4Wj",
		end: "00:00",
		price: 30,
		description:
			"Dogleg was an American post-hardcore band formed in Detroit, Michigan in 2015. They released their debut album, Melee in 2020 to critical acclaim. The band is fronted by Alex Stoitsiadis as lead vocalist and rhythm guitarist, with Chase Macinski on bass, Parker Grissom on guitar, and Jacob Hanlon on drums.",
		id: "54",
		genre: "Punk",
		start: "22:30",
		bandName: "Dogleg",
	},
	{
		date: "25-03-2022",
		venue_id: 23,
		spotify: "https://open.spotify.com/artist/73A3bLnfnz5BoQjb4gNCga",
		end: "00:00",
		price: 25,
		description:
			"Bicep are an electronic music production and DJ duo from Belfast, Northern Ireland, consisting of Andrew Ferguson and Matthew McBriar.",
		id: "79",
		genre: "Electronic",
		start: "20:00",
		bandName: "Bicep",
	},
	{
		date: "11-03-2022",
		venue_id: 29,
		spotify: "https://open.spotify.com/artist/4kSGbjWGxTchKpIxXPJv0B",
		end: "23:30",
		price: 35,
		description:
			"Crumb is an American psychedelic rock band. The group is a collaboration of Brooklyn-based musicians Lila Ramani, Jesse Brotter, Bri Aronow, and Jonathan Gilad, who met while attending Tufts University.",
		id: "8",
		genre: "Rock",
		start: "21:00",
		bandName: "Crumb",
	},
	{
		date: "26-03-2022",
		venue_id: 3,
		spotify: "https://open.spotify.com/artist/3LmkRGuUav9Un8TDMjwKSg",
		end: "23:30",
		price: 10,
		description:
			"Skengdo & AM, whose real names are Terrell Doyley and Joshua Malinga, respectively, are a British drill duo from Brixton, London. They are both members of the UK drill group and alleged gang, 410. The group is known to have conflict with neighbouring Harlem Spartans, based in Kennington.",
		id: "66",
		genre: "Hip Hop",
		start: "21:30",
		bandName: "Skengdo & AM",
	},
	{
		date: "18-03-2022",
		venue_id: 16,
		spotify: "https://open.spotify.com/artist/16eRpMNXSQ15wuJoeqguaB",
		end: "23:45",
		price: 20,
		description:
			"The Flaming Lips are an American psychedelic rock band formed in 1983 in Oklahoma City, Oklahoma. The band currently consists of Wayne Coyne, Steven Drozd, Derek Brown, Matt Duckworth Kirksey and Nicholas Ley. The group recorded several albums and EPs on an indie label, Restless, in the 1980s and early 1990s.",
		id: "48",
		genre: "Rock",
		start: "21:30",
		bandName: "The Flaming Lips",
	},
	{
		date: "13-03-2022",
		venue_id: 28,
		spotify: "https://open.spotify.com/artist/7Hvq85OU8T7Hsd63zNBwaL",
		end: "23:45",
		price: 45,
		description:
			"Black Midi are an English rock band from London, formed in 2017. The band currently consists of Geordie Greep, Cameron Picton and Morgan Simpson. Seth Evans and Kaidi Akinnibi have been frequent collaborators in both studio and live performances since 2020.",
		id: "9",
		genre: "Rock",
		start: "21:15",
		bandName: "Black Midi",
	},
	{
		date: "20-03-2022",
		venue_id: 26,
		spotify: "https://open.spotify.com/artist/6VsiDFMZJlJ053P1uO4A6h",
		end: "01:00",
		description:
			"Public Service Broadcasting are a London-based musical group consisting of: J. Willgoose, Esq. on guitar, banjo, other stringed instruments, samplings and electronic musical instruments; Wrigglesworth on drums, piano and electronic musical instruments; and J F Abraham on flugelhorn, bass guitar, drums and assorted other instruments including a vibraslap.",
		id: "59",
		price: 8,
		genre: "Electronic",
		bandName: "Public Service Broadcasting",
		start: "23:00",
	},
	{
		date: "13-03-2022",
		venue_id: 2,
		spotify: "https://open.spotify.com/artist/4tZwfgrHOc3mvqYlEYSvVi",
		end: "23:00",
		description:
			"Daft Punk are a French electronic music duo formed in 1993 in Paris by Guy-Manuel de Homem-Christo and Thomas Bangalter. Widely regarded as one of the greatest and most influential acts in dance music history, they achieved popularity in the late 1990s as part of the French house movement. They garnered critical acclaim and commercial success in the years following, combining elements of house music with funk, techno, disco, indie rock and pop.",
		id: "1",
		price: 15,
		genre: "Electronic",
		bandName: "Daft Punk",
		start: "21:00",
	},
	{
		date: "11-03-2022",
		venue_id: 6,
		spotify: "https://open.spotify.com/artist/240wlM8vDrf6S4zCyzGj2W",
		end: "23:55",
		price: 28,
		description:
			"CamelPhat are an English DJ and production duo, consisting of Dave Whelan and Mike Di Scala, formed in Liverpool in 2004. They are best known for the 2017 single Cola, which peaked at number 3 in the UK Dance Chart, and at number 18 in the UK Singles Chart.",
		id: "31",
		genre: "Electronic",
		start: "21:30",
		bandName: "CamelPhat",
	},
	{
		date: "27-03-2022",
		venue_id: 20,
		spotify: "https://open.spotify.com/artist/6sFIWsNpZYqfjUpaCgueju",
		end: "00:00",
		price: 25,
		description:
			"Carly Rae Jepsen is a Canadian singer, songwriter, and actress. Born and raised in Mission, British Columbia, Jepsen pursued a musical theatre program at the Canadian College of Performing Arts in Victoria, British Columbia.",
		id: "80",
		genre: "Pop",
		start: "23:00",
		bandName: "Carly Rae Jepsen",
	},
	{
		date: "11-03-2022",
		venue_id: 1,
		spotify: "https://open.spotify.com/artist/34EP7KEpOjXcM2TCat1ISk",
		end: "18:00",
		description:
			"Wu-Tang Clan is an American hip hop group formed in Staten Island, New York City, in 1992. Its original members include RZA, GZA, Ol' Dirty Bastard, Method Man, Raekwon, Ghostface Killah, Inspectah Deck, U-God, and Masta Killa. Close affiliate Cappadonna later became an official member. Wu-Tang Clan are regarded as a highly influential group in hip hop, helping to popularize and develop the East Coast hip hop and hardcore hip hop styles.",
		id: "6",
		price: 29.99,
		genre: "Hip Hop",
		bandName: "Wu Tang Clan",
		start: "15:15",
	},
	{
		date: "19-03-2022",
		venue_id: 29,
		spotify: "https://open.spotify.com/artist/5VadK1havLhK1OpKYsXv9y",
		end: "22:45",
		price: 13,
		description:
			"D-Block Europe, often abbreviated to DBE, is a British hip hop collective consisting of Adam Nathaniel Young Adz Williams, Ricky Earl Dirtbike LB Banton and Lil Pino from Lewisham, London. Their name is a reference to The Lox. They started to put out tracks on their own label in the beginning of 2014.",
		id: "62",
		genre: "Hip Hop",
		start: "21:15",
		bandName: "D-Block Europe",
	},
	{
		date: "25-03-2022",
		venue_id: 28,
		spotify: "https://open.spotify.com/artist/0HlxL5hisLf59ETEPM3cUA",
		end: "01:40",
		price: 23,
		description:
			"Scooter is a German happy hardcore, rave and techno music band founded in Hamburg in 1993. To date, the band has sold over 30 million records and earned over 80 Gold and Platinum awards. Scooter is considered the most commercially successful German single-record act with 23 top ten hits.",
		id: "75",
		genre: "Electronic",
		start: "23:40",
		bandName: "Scooter",
	},
	{
		date: "26-03-2022",
		venue_id: 26,
		spotify: "https://open.spotify.com/artist/54QMjE4toDfiCryzYWCpXX",
		end: "01:40",
		price: 25,
		description:
			"Metronomy are an English electronic music group formed in 1999. As of 2021, the band consists of Joseph Mount, Oscar Cash, Anna Prior, Olugbenga Adelekan and Michael Lovett. Their music consists of vocal and instrumental electronic pop music.",
		id: "76",
		genre: "Electronic",
		start: "23:40",
		bandName: "Metronomy",
	},
	{
		date: "27-03-2022",
		venue_id: 10,
		spotify: "https://open.spotify.com/artist/6KImCVD70vtIoJWnq6nGn3",
		end: "21:30",
		price: 53,
		description:
			"Harry Edward Styles is an English singer, songwriter and actor. His musical career began in 2010 as a solo contestant on the British music competition series The X Factor.",
		id: "84",
		genre: "Pop",
		start: "19:00",
		bandName: "Harry Styles",
	},
	{
		date: "19-03-2022",
		venue_id: 27,
		spotify: "https://open.spotify.com/artist/5HAtRoEPUvGSA7ziTGB1cF",
		end: "02:00",
		price: 8,
		description:
			"The Orb are an electronic music group founded in 1988 by Alex Paterson and Jimmy Cauty. Known for their psychedelic sound, the Orb developed a cult following among clubbers coming down from drug-induced highs.",
		id: "60",
		genre: "Electronic",
		start: "23:00",
		bandName: "The Orb",
	},
	{
		date: "20-03-2022",
		venue_id: 28,
		spotify: "https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ",
		end: "01:30",
		price: 27,
		description:
			"Abel Makkonen Tesfaye, known professionally as the Weeknd, is a Canadian singer-songwriter and record producer. Known for his sonic versatility and dark lyricism, Tesfaye's music explores escapism, romance, and melancholia, and is often inspired by personal experiences.",
		id: "61",
		genre: "Hip Hop",
		start: "23:15",
		bandName: "The Weeknd",
	},

	// stopping point
	{
		date: "20-03-2022",
		venue_id: 6,
		spotify: "https://open.spotify.com/artist/2nszamLjZFgu3Yx77mKxuC",
		end: "23:30",
		price: 22.5,
		description:
			"Unkle is a British musical outfit founded in 1992 by James Lavelle. Originally categorised as trip hop, the group once included producer DJ Shadow and have employed a variety of guest artists and producers.",
		id: "38",
		genre: "Electronic",
		start: "21:30",
		bandName: "Unkle",
	},
	{
		date: "13-03-2022",
		venue_id: 9,
		spotify: "https://open.spotify.com/artist/7wJ9NwdRWtN92NunmXuwBk",
		end: "23:00",
		price: 30,
		description:
			"Orchestral Manoeuvres in the Dark are an English electronic band formed in Wirral, Merseyside, in 1978. The group consists of co-founders Andy McCluskey and Paul Humphreys, along with Martin Cooper and Stuart Kershaw; McCluskey has been the only constant member.",
		id: "28",
		genre: "Electronic",
		start: "20:30",
		bandName: "Orchestral Manoeuvres in the Dark",
	},
	{
		date: "19-03-2022",
		venue_id: 20,
		spotify: "https://open.spotify.com/artist/7DlD7rLG9MKuvXtTeACzkO",
		end: "21:45",
		price: 30,
		description:
			"Dry Cleaning are an English post-punk band who formed in South London in 2018. The band is composed of vocalist Florence Shaw, guitarist Tom Dowse, bassist Lewis Maynard and drummer Nick Buxton. They are noted for their use of spoken word primarily in lieu of sung vocals, as well as their unconventional lyrics.",
		id: "53",
		genre: "Rock",
		start: "18:30",
		bandName: "Dry Cleaning",
	},
	{
		date: "26-03-2022",
		venue_id: 18,
		spotify: "https://open.spotify.com/artist/2h3ooJn8m8X8cL2g1BZ1Rd",
		end: "20:00",
		price: 6,
		description:
			"Yard Act are a British rock band from Leeds, comprising James Smith, Ryan Needham, Sam Shjipstone and Jay Russell. Their debut album The Overload was released on 21 January 2022 and debuted at number 2 on the UK Albums Chart.",
		id: "82",
		genre: "Rock",
		start: "18:00",
		bandName: "Yard Act",
	},
	{
		date: "12-03-2022",
		venue_id: 7,
		spotify: "https://open.spotify.com/artist/6nS5roXSAGhTGr34W6n7Et",
		end: "23:30",
		price: 25,
		description:
			"Disclosure is an English electronic music duo consisting of brothers Howard and Guy Lawrence. They grew up in Reigate, Surrey. Their debut studio album, Settle, released on 3 June 2013, by PMR Records, was nominated for Best Dance/Electronica Album at the 2014 Grammy Awards.",
		id: "30",
		genre: "Electronic",
		start: "21:00",
		bandName: "Disclosure",
	},
	{
		date: "20-03-2022",
		venue_id: 3,
		spotify: "https://open.spotify.com/artist/2qhmNI4ZHPpeDutdg473Z3",
		end: "03:00",
		price: 10,
		description:
			"The Future Sound of London is a British electronic music duo composed of Garry Cobain and Brian Dougans. Described as a boundary-pushing electronic act by AllMusic, their work covers many areas of electronic music, such as techno, ambient, house music, trip hop, psychedelia, and dub.",
		id: "35",
		genre: "Electronic",
		start: "22:00",
		bandName: "The Future Sound of London",
	},
	{
		date: "18-03-2022",
		venue_id: 19,
		spotify: "https://open.spotify.com/artist/37PL04N8kBWWW69jdrMMWT",
		end: "21:45",
		price: 25,
		description:
			"Altın Gün is an Anatolian rock band from Amsterdam, Netherlands. It was founded by bassist Jasper Verhulst in 2016 when he posted an ad on Facebook looking for Turkish musicians.",
		id: "52",
		genre: "Rock",
		start: "18:30",
		bandName: "Altın Gün",
	},
	{
		date: "12-03-2022",
		venue_id: 13,
		spotify: "https://open.spotify.com/artist/762310PdDnwsDxAQxzQkfX",
		end: "21:00",
		price: 50,
		description:
			"Depeche Mode are an English electronic music band formed in Basildon in 1980. The group consists of a trio of Dave Gahan, Martin Gore and Andy Fletcher. Depeche Mode released their debut album, Speak & Spell, in 1981, bringing the band onto the British new wave scene.",
		id: "24",
		genre: "Electronic",
		start: "18:00",
		bandName: "Depeche Mode",
	},
	{
		date: "26-03-2022",
		venue_id: 25,
		spotify: "https://open.spotify.com/artist/4D75GcNG95ebPtNvoNVXhz",
		end: "01:40",
		price: 28,
		description:
			"Nick Leonardus van de Wall, better known as Afrojack, is a Dutch DJ, record producer and remixer from Spijkenisse. In 2007, he founded the record label Wall Recordings; his debut album Forget the World was released in 2014.",
		id: "77",
		genre: "Electronic",
		start: "23:00",
		bandName: "Afrojack",
	},
	{
		date: "25-03-2022",
		venue_id: 19,
		spotify: "https://open.spotify.com/artist/01XYiBYaoMJcNhPokrg0l0",
		end: "20:00",
		price: 80,
		description:
			"STAYC is a South Korean girl group formed by High Up Entertainment. The group is composed of six members: Sumin, Sieun, Isa, Seeun, Yoon, and J. They debuted on November 12, 2020, with the release of their debut single album Star to a Young Culture.",
		id: "81",
		genre: "Pop",
		start: "18:00",
		bandName: "STAYC",
	},
	{
		date: "12-03-2022",
		venue_id: 10,
		spotify: "https://open.spotify.com/artist/4Y7tXHSEejGu1vQ9bwDdXW",
		end: "23:00",
		price: 29.99,
		description:
			"Norman Quentin Cook, also known by his stage name Fatboy Slim, is an English musician, DJ and record producer who helped to popularise the big beat genre in the 1990s.",
		id: "27",
		genre: "Electronic",
		start: "20:30",
		bandName: "Fatboy Slim",
	},
	{
		date: "26-03-2022",
		venue_id: 15,
		spotify: "https://open.spotify.com/artist/0wz0jO9anccPzH04N7FLBH",
		end: "21:00",
		price: 14,
		description:
			"Low is an American indie rock band from Duluth, Minnesota, formed in 1993. The group is composed of founding members Alan Sparhawk and Mimi Parker.",
		id: "71",
		genre: "Indie",
		start: "19:00",
		bandName: "Low",
	},
	{
		date: "12-03-2022",
		venue_id: 4,
		spotify: "https://open.spotify.com/artist/1GLtl8uqKmnyCWxHmw9tL4",
		end: "22:30",
		description:
			'The Kooks are an English indie rock band formed in 2004 in Brighton. The band consists of Luke Pritchard (vocals/rhythm guitar), Hugh Harris (lead guitar/synthesizer/bass) and Alexis Nunez (drums).\n\nTheir music is primarily influenced by the 1960s British Invasion movement and post-punk revival of the new millennium. The Kooks have experimented in several genres including rock, Britpop, pop, reggae, ska, and more recently, funk and hip-hop, being described once as a "more energetic Thrills or a looser Sam Roberts Band, maybe even a less severe Arctic Monkeys at times".',
		id: "5",
		price: 18.5,
		genre: "Indie",
		bandName: "Kooks",
		start: "20:00",
	},
	{
		date: "13-03-2022",
		venue_id: 5,
		spotify: "https://open.spotify.com/artist/5M52tdBnJaKSvOpJGz8mfZ",
		end: "23:45",
		description:
			"Black Sabbath are an English rock band formed in Birmingham in 1968 by guitarist Tony Iommi, drummer Bill Ward, bassist Geezer Butler and vocalist Ozzy Osbourne. They are often cited as pioneers of heavy metal music. The band helped define the genre with releases such as Black Sabbath (1970), Paranoid (1970), and Master of Reality (1971). The band had multiple line-up changes following Osbourne's departure in 1979, with Iommi being the only constant member throughout its history.",
		id: "4",
		price: 83,
		genre: "Metal",
		bandName: "Black Sabeth",
		start: "19:30",
	},
	{
		date: "20-03-2022",
		venue_id: 12,
		spotify: "https://open.spotify.com/artist/1oPRcJUkloHaRLYx0olBLJ",
		end: "23:00",
		price: 17.5,
		description:
			"Magdalena Bay is an American synth-pop and electronic duo from Miami, Florida based in Los Angeles, California. The band consists of singer-songwriter Mica Tenenbaum and producer Matthew Lewin.",
		id: "44",
		genre: "Pop",
		start: "20:00",
		bandName: "Magdalena Bay",
	},
	{
		date: "11-03-2022",
		venue_id: 6,
		spotify: "https://open.spotify.com/artist/7qdsk0UXx2jCX7jbp6rxeq",
		end: "21:00",
		price: 12,
		description:
			"The Black Dog is a British electronic music group, founded in 1989 by Ken Downie along with Ed Handley and Andy Turner. The group are considered pioneering figures of techno's ruminative home-listening aesthetic in the early 1990s.",
		id: "32",
		genre: "Electronic",
		start: "18:30",
		bandName: "The Black Dog",
	},
	{
		date: "20-03-2022",
		venue_id: 9,
		spotify: "https://open.spotify.com/artist/2TwOrUcYnAlIiKmVQkkoSZ",
		end: "22:30",
		price: 5,
		description:
			"Wet Leg are a British indie band from the Isle of Wight, founded by Rhian Teasdale and Hester Chambers.",
		id: "41",
		genre: "Indie",
		start: "19:30",
		bandName: "Wet Leg",
	},
	{
		date: "19-03-2022",
		venue_id: 18,
		spotify: "https://open.spotify.com/artist/43O3c6wewpzPKwVaGEEtBM",
		end: "21:45",
		price: 25,
		description:
			"My Morning Jacket is an American rock band formed in Louisville, Kentucky in 1998. The band consists of vocalist/guitarist Jim James, bassist Tom Blankenship, drummer Patrick Hallahan, guitarist Carl Broemel, and keyboardist Bo Koster.",
		id: "51",
		genre: "Rock",
		start: "18:30",
		bandName: "My Morning Jacket",
	},
	{
		date: "25-03-2022",
		venue_id: 24,
		spotify: "https://open.spotify.com/artist/3iOvXCl6edW5Um0fXEBRXy",
		end: "01:00",
		price: 28,
		description:
			"The xx are an English indie rock band from Wandsworth, London, formed in 2005. The band consists of Romy Madley Croft, Oliver Sim, Jamie Smith, also known as Jamie xx, and formerly Baria Qureshi.",
		id: "78",
		genre: "Indie",
		start: "23:00",
		bandName: "The xx",
	},
	{
		date: "26-03-2022",
		venue_id: 16,
		spotify: "https://open.spotify.com/artist/6FQqZYVfTNQ1pCqfkwVFEa",
		end: "20:00",
		price: 60,
		description:
			"Foals are a British rock band formed in Oxford. The band's current line-up consists of Greek-born lead vocalist and guitarist Yannis Philippakis, drummer and percussionist Jack Bevan and rhythm guitarist Jimmy Smith.",
		id: "83",
		genre: "Rock",
		start: "18:00",
		bandName: "Foals",
	},
	{
		date: "27-03-2022",
		venue_id: 5,
		spotify: "https://open.spotify.com/artist/31Ua7zSTJxegjyd49ujbSA",
		end: "23:30",
		price: 12,
		description:
			"NSG is a British afroswing collective from East London. The group consists of Kruddz, OGD, Papii Abz, Dope, Mxjib, and Mojo. They released two mixtapes, Grown Up and Roots, the latter includes their most successful single Options featuring Tion Wayne.",
		id: "68",
		genre: "Hip Hop",
		start: "21:00",
		bandName: "NSG",
	},
	{
		date: "26-03-2022",
		venue_id: 2,
		spotify: "https://open.spotify.com/artist/47rT8CoKTbr0S945AGgATQ",
		end: "22:30",
		price: 10,
		description:
			"Darren Diggs, known professionally as DigDat, is a British rapper. His single Air Force entered the UK Singles Chart at number 93 in September 2018.",
		id: "65",
		genre: "Hip Hop",
		start: "20:30",
		bandName: "DigDat",
	},
	{
		date: "19-03-2022",
		venue_id: 2,
		spotify: "https://open.spotify.com/artist/38DX4hQVvPBs3PThDIAK11",
		end: "20:00",
		price: 30,
		description:
			"Carbon Based Lifeforms is a Swedish electronic music duo formed in 1996 in Gothenburg by Johannes Hedberg and Daniel Vadestrid.",
		id: "34",
		genre: "Electronic",
		start: "18:00",
		bandName: "Carbon Based Lifeforms",
	},
	{
		date: "13-03-2022",
		venue_id: 14,
		spotify: "https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms",
		end: "21:00",
		price: 120,
		description:
			"Stefani Joanne Angelina Germanotta, known professionally as Lady Gaga, is an American singer, songwriter, and actress. She is known for her image reinventions and musical versatility. Gaga began performing as a teenager, singing at open mic nights and acting in school plays.",
		id: "23",
		genre: "Pop",
		start: "17:00",
		bandName: "Lady Gaga",
	},
	{
		date: "18-03-2022",
		venue_id: 25,
		spotify: "https://open.spotify.com/artist/4tNxq9NGKTKaX8OkZBLgf0",
		end: "01:00",
		description:
			"George Evelyn, better known by his stage name Nightmares on Wax or DJ E.A.S.E., is an English DJ and record producer from Leeds. His music has been released by Warp Records. He is based in Ibiza. Nightmares on Wax were originally a group consisting of Evelyn and John Halnon, and then later with Kevin Harper.",
		id: "58",
		price: 5,
		genre: "Electronic",
		bandName: "Nightmares on Wax",
		start: "23:00",
	},
	{
		date: "19-03-2022",
		venue_id: 14,
		spotify: "https://open.spotify.com/artist/2dfxY7YDuYCUtWFzWTS6IR",
		end: "23:30",
		price: 20,
		description:
			"Foxing is an American indie rock band from St. Louis, Missouri. The band has released four studio albums and an EP, as well as a pair of split albums and a single.",
		id: "46",
		genre: "Rock",
		start: "20:30",
		bandName: "Foxing",
	},
	{
		date: "13-03-2022",
		venue_id: 18,
		spotify: "https://open.spotify.com/artist/4I29IR2MABOOQXGDdcYA2q",
		end: "01:00",
		description:
			"Another Michael is an American indie rock band from Philadelphia, Pennsylvania. The band is currently signed to Run for Cover Records.",
		id: "19",
		price: 24.99,
		genre: "Rock",
		bandName: "Another Michael",
		start: "22:45",
	},
	{
		date: "11-03-2022",
		venue_id: 11,
		spotify: "https://open.spotify.com/artist/4VNQWV2y1E97Eqo2D5UTjx",
		end: "23:00",
		price: 19.99,
		description:
			"Gorgon City are an English electronic music production duo consisting of two North London producers Kye Gibbon and Matt Robson-Scott. Their 2013 debut single peaked at number 44 on the UK Singles Chart.",
		id: "26",
		genre: "Electronic",
		start: "20:00",
		bandName: "Gorgon City",
	},

	// stopping point
	{
		date: "19-03-2022",
		venue_id: 22,
		spotify: "https://open.spotify.com/artist/2mVVjNmdjXZZDvhgQWiakk",
		end: "00:00",
		price: 15,
		description:
			"Khruangbin is an American musical trio from Houston, Texas. The band comprises Laura Lee on bass, Mark Speer on guitar, and Donald Ray DJ Johnson Jr. on drums. The band is known for blending global music influences, such as classic soul, dub, rock and psychedelia.",
		id: "55",
		genre: "Rock",
		start: "22:30",
		bandName: "Khruangbin",
	},
	{
		date: "12-03-2022",
		venue_id: 30,
		spotify: "https://open.spotify.com/artist/4bzfsZhaLW6VWHLh1sqcrK",
		end: "23:30",
		price: 30,
		description:
			"Meet Me at the Altar is an American pop punk band formed in 2015. Initially, the three members—all of whom lived in different states at the time—worked on music remotely through the internet. The band went on their first tour in 2018, and were signed by Fueled by Ramen in 2020",
		id: "7",
		genre: "Pop",
		start: "22:00",
		bandName: "Meet Me at the Altar",
	},
	{
		date: "20-03-2022",
		venue_id: 23,
		spotify: "https://open.spotify.com/artist/25CgccXK9hJBTuaMF44zeR",
		end: "00:00",
		price: 15,
		description:
			"The Spirit of the Beehive is an American band from Philadelphia, Pennsylvania. The band name comes from 1973 Spanish film of the same name. The band features Zack Schwartz, formerly of the band Glocca Morra. Their debut self-titled album was released in 2014. An EP entitled You Are Arrived, was released in 2015.",
		id: "56",
		genre: "Rock",
		start: "22:45",
		bandName: "The Spirit of the Beehive",
	},
	{
		date: "12-03-2022",
		venue_id: 26,
		spotify: "https://open.spotify.com/artist/4AzAfQNuAyKOFG4DZMsdAo",
		end: "22:00",
		price: 25.5,
		description:
			"The Snuts are a Scottish indie rock band formed in 2015, originating from West Lothian, Scotland. They have performed across the United Kingdom and Ireland. The band consists of Jack Cochrane, Joe McGillveray, Callum '29' Wilson and Jordan 'Joko' Mackay and was formed when the members were in school.",
		id: "11",
		genre: "Rock",
		start: "20:00",
		bandName: "The Snuts",
	},
	{
		date: "12-03-2022",
		venue_id: 1,
		spotify: "https://open.spotify.com/artist/2ye2Wgw4gimLv2eAKyk1NB",
		end: "21:00",
		description:
			"Metallica is an American heavy metal band. The band was formed in 1981 in Los Angeles by vocalist/guitarist James Hetfield and drummer Lars Ulrich, and has been based in San Francisco for most of its career. The band's fast tempos, instrumentals and aggressive musicianship made them one of the founding \"big four\" bands of thrash metal, alongside Megadeth, Anthrax and Slayer. Metallica's current lineup comprises founding members and primary songwriters Hetfield and Ulrich, longtime lead guitarist Kirk Hammett and bassist Robert Trujillo. Guitarist Dave Mustaine (who went on to form Megadeth after being fired from the band) and bassists Ron McGovney, Cliff Burton and Jason Newsted are former members of the band.",
		id: "3",
		price: 35,
		genre: "Metal",
		bandName: "Metalica",
		start: "18:00",
	},
	{
		date: "25-03-2022",
		venue_id: 7,
		spotify: "https://open.spotify.com/artist/0M7GyeyRi2fG8c1LdP4jhi",
		end: "23:00",
		description:
			"Lastlings are an Australian electronic pop band from Gold Coast, Queensland made up of brother and sister duo Amy and Josh Dowdle. They have performed at Coachella, Spilt Milk, Splendour in the Grass, and The Plot.",
		id: "70",
		price: 15,
		genre: "Pop",
		bandName: "Lastlings",
		start: "21:00",
	},
	{
		date: "25-03-2022",
		venue_id: 11,
		spotify: "https://open.spotify.com/artist/3MdG05syQeRYPPcClLaUGl",
		end: "21:30",
		price: 70,
		description:
			"Diana Ross is an American singer, songwriter and actress, born in Detroit, Michigan. She rose to fame as the lead singer of the vocal group the Supremes, who became Motown's most successful act during the 1960s and one of the world's best-selling girl groups of all time.",
		id: "85",
		genre: "Pop",
		start: "19:00",
		bandName: "Diana Ross",
	},
	{
		date: "25-03-2022",
		venue_id: 6,
		spotify: "https://open.spotify.com/artist/0tPKcpC8yXpfdWXFcN7Vwr",
		end: "23:00",
		price: 15,
		description:
			"Courtney Leon Freckleton, known professionally as Nines, is a British rapper. After releasing a string of mixtapes between 2011 and 2015, Nines signed to XL Recordings and released his debut album One Foot Out, which charted at number 4 in the UK Albums Chart.",
		id: "69",
		genre: "Hip Hop",
		start: "21:00",
		bandName: "Nines",
	},
	{
		date: "11-03-2022",
		venue_id: 17,
		spotify: "https://open.spotify.com/artist/7BDvurihyagH0uSPNDJX7d",
		end: "23:00",
		description:
			"Pillow Queens are an Irish indie rock band from Dublin, formed in 2016. The band is composed of co-lead vocalists Sarah Corcoran and Pamela Connolly, lead guitarist Cathy McGuiness and drummer Rachel.",
		id: "20",
		price: 29.99,
		genre: "Rock",
		bandName: "Pillow Queens",
		start: "21:45",
	},
	{
		date: "18-03-2022",
		venue_id: 7,
		spotify: "https://open.spotify.com/artist/4NZM5xKuDpGc4vEHDwGO1Q",
		end: "23:30",
		price: 33.8,
		description:
			"DJ Food is an electronic music project currently headed by Kevin Foakes. Originally conceived by the members of Coldcut on the Ninja Tune independent record label, the project started in 1990 on the premise of providing metaphorical food for DJs.",
		id: "39",
		genre: "Electronic",
		start: "22:30",
		bandName: "DJ Food",
	},
	{
		date: "18-03-2022",
		venue_id: 13,
		spotify: "https://open.spotify.com/artist/3PP6ghmOlDl2jaKaH0avUN",
		end: "23:00",
		price: 17.5,
		description:
			"Black Country, New Road are an English rock band formed in Cambridgeshire in 2018, consisting of Tyler Hyde, Lewis Evans, Georgia Ellery, May Kershaw, Charlie Wayne and Luke Mark. The band's first two albums featured guitarist and lead vocalist Isaac Wood, who left the band in 2022.",
		id: "45",
		genre: "Rock",
		start: "20:00",
		bandName: "Black Country, New Road",
	},
	{
		date: "25-03-2022",
		venue_id: 30,
		spotify: "https://open.spotify.com/artist/2XnBwblw31dfGnspMIwgWz",
		end: "21:40",
		price: 21,
		description:
			"Axel Christofer Hedfors, better known by his stage name Axwell, is a Swedish DJ, record producer, remixer and owner of Axtone Records. He is a member of Swedish House Mafia along with Sebastian Ingrosso and Steve Angello.",
		id: "74",
		genre: "Electronic",
		start: "19:40",
		bandName: "Axwell",
	},
	{
		date: "19-03-2022",
		venue_id: 5,
		spotify: "https://open.spotify.com/artist/5akVqMzdZOdbMYbE4vNZWD",
		end: "01:00",
		price: 12.5,
		description:
			"Plaid are an English electronic music duo composed of Andy Turner and Ed Handley. They were founding members of The Black Dog and used many other names, such as Atypic and Balil, before settling on Plaid.",
		id: "37",
		genre: "Electronic",
		start: "21:00",
		bandName: "Plaid",
	},
	{
		date: "11-03-2022",
		venue_id: 8,
		spotify: "https://open.spotify.com/artist/1o43SzzuLoyOxqThmp7s0g",
		end: "23:00",
		price: 34.99,
		description:
			"Austra is a Canadian electronic music band from Toronto, Ontario, founded in 2009 by composer, singer-songwriter, and producer Katie Stelmanis. Stelmanis is the only permanent member of the project, with a rotating live band that has included Maya Postepski, Dorian Wolf, and Ryan Wonsiak.",
		id: "29",
		genre: "Pop",
		start: "21:00",
		bandName: "Austra",
	},
	{
		date: "12-03-2022",
		venue_id: 16,
		spotify: "https://open.spotify.com/artist/1Cs0zKBU1kc0i8ypK3B9ai",
		end: "23:30",
		description:
			"Pierre David Guetta is a French DJ, record producer and songwriter. He has racked up over 50 million record sales globally, with more than 10 billion streams. In 2011, 2020 and 2021, Guetta was voted the number one DJ in the DJ Mag Top 100 DJs poll.",
		id: "21",
		price: 29.99,
		genre: "Electronic",
		bandName: "David Guetta",
		start: "21:45",
	},
	{
		date: "13-03-2022",
		venue_id: 12,
		spotify: "https://open.spotify.com/artist/5CdJjUi9f0cVgo9nFuJrFa",
		end: "21:00",
		price: 10,
		description:
			"Adventure Club is a Canadian electronic dance music duo composed of Christian Srigley and Leighton James, based out of Montreal, Quebec. The duo began as a hardcore pop-punk band before venturing into electronic dance music in 2011.",
		id: "25",
		genre: "Electronic",
		start: "19:00",
		bandName: "Adventure Club",
	},
	{
		date: "11-03-2022",
		venue_id: 25,
		spotify: "https://open.spotify.com/artist/3ZztVuWxHzNpl0THurTFCv",
		end: "21:00",
		price: 15,
		description:
			"Architects are a British metalcore band from Brighton, East Sussex, formed in 2004 by twin brothers Dan and Tom Searle. The band now consists of Dan Searle on drums, Sam Carter on vocals, Alex Dean on bass, and Adam Christianson and Josh Middleton on guitars. They have been signed to Epitaph Records since 2013.",
		id: "12",
		genre: "Rock",
		start: "19:00",
		bandName: "Architects",
	},
	{
		date: "11-03-2022",
		venue_id: 20,
		spotify: "https://open.spotify.com/artist/4MVyzYMgTwdP7Z49wAZHx0",
		end: "23:45",
		price: 15,
		description:
			"Lynyrd Skynyrd is an American rock band formed in Jacksonville, Florida. The group originally formed as My Backyard in 1964 and comprised Ronnie Van Zant, Gary Rossington, Allen Collins, Larry Junstrom and Bob Burns.",
		id: "17",
		genre: "Rock",
		start: "21:45",
		bandName: "Lynyrd Skynyrd",
	},
	{
		date: "25-03-2022",
		venue_id: 4,
		spotify: "https://open.spotify.com/artist/31lnFZEM6ysvjOx59VyxRE",
		end: "23:30",
		price: 12,
		description:
			"Krept and Konan is a British hip hop duo from London, consisting of Casyo Valentine Krept Johnson BEM and Karl Dominic Konan Wilson BEM, the son of Delroy Wilson otherwise known as 'Jamaica's first child star'. Their first major release was the mixtape Young Kingz, released on 2 September 2013.",
		id: "67",
		genre: "Hip Hop",
		start: "21:30",
		bandName: "Krept & Konan",
	},
	{
		date: "11-03-2022",
		venue_id: 27,
		spotify: "https://open.spotify.com/artist/1yhTALwId0bpL1U1XRT3Zs",
		end: "22:30",
		price: 20,
		description:
			"Pom Pom Squad is an indie rock/grunge band from Brooklyn, New York. Begun in 2015 as a solo project of frontwoman Mia Berrin, Pom Pom Squad evolved into a four-piece band consisting of Berrin, bassist Mari Alé Figeman, drummer Shelby Keller, and guitarist Alex Mercuri.",
		id: "10",
		genre: "Indie",
		start: "20:15",
		bandName: "Pom Pom Squad",
	},
	{
		date: "18-03-2022",
		venue_id: 24,
		spotify: "https://open.spotify.com/artist/7GRrLcUxwtQLvOpO7OHO80",
		end: "00:00",
		price: 5,
		description:
			"Psychedelic Porn Crumpets is an Australian psychedelic rock band formed in 2014 in Perth. Members include Jack McEwan, Luke Parish, Danny Caddy, Luke Reynolds, and Chris Young, who began playing together in an old horse barn in rural Leederville.",
		id: "57",
		genre: "Rock",
		start: "23:00",
		bandName: "Psychedelic Porn Crumpets",
	},
	{
		date: "19-03-2022",
		venue_id: 15,
		spotify: "https://open.spotify.com/artist/2S5hlvw4CMtMGswFtfdK15",
		end: "23:30",
		price: 20,
		description:
			"Royal Blood are an English rock duo formed by Mike Kerr and Ben Thatcher in Worthing in 2011. Their sound is anchored by Kerr's unique bass playing style, which sees him using various effects pedals and amps to make his bass guitar sound like a standard electric guitar and bass guitar at the same time.",
		id: "47",
		genre: "Rock",
		start: "20:30",
		bandName: "Royal Blood",
	},
	{
		date: "11-03-2022",
		venue_id: 22,
		spotify: "https://open.spotify.com/artist/0NZsNnETGPWLKJj2Y0vpBx",
		end: "23:45",
		price: 15,
		description:
			"Chai are a Japanese rock band from Nagoya. The group consists of four women—Mana, Kana, Yuuki and Yuna. Formed in 2012, the band released their debut studio album Pink in 2017.",
		id: "15",
		genre: "Rock",
		start: "21:00",
		bandName: "Chai",
	},
	{
		date: "18-03-2022",
		venue_id: 10,
		spotify: "https://open.spotify.com/artist/2qnpHrOzdmOo1S4ox3j17x",
		end: "02:30",
		price: 5.5,
		description:
			"Turnstile is an American hardcore punk band from Baltimore, Maryland, formed in 2010. They have released five EPs and three studio albums.",
		id: "42",
		genre: "Punk",
		start: "22:00",
		bandName: "Turnstile",
	},
	{
		date: "19-03-2022",
		venue_id: 11,
		spotify: "https://open.spotify.com/artist/3btzEQD6sugImIHPMRgkwV",
		end: "22:30",
		price: 5.5,
		description:
			"Wolf Alice are an English alternative rock band from London, England. Formed in 2010 as an acoustic duo comprising singer Ellie Rowsell and guitarist Joff Oddie, since 2012 Wolf Alice have also featured bassist Theo Ellis and drummer Joel Amey.",
		id: "43",
		genre: "Rock",
		start: "20:00",
		bandName: "Wolf Alice",
	},
	{
		date: "12-03-2022",
		venue_id: 24,
		spotify: "https://open.spotify.com/artist/7jy3rLJdDQY21OgRLCZ9sD",
		end: "21:45",
		price: 75,
		description:
			"Foo Fighters are an American rock band formed in Seattle, Washington, in 1994. The band was founded by former Nirvana drummer Dave Grohl as a one-man project following the dissolution of Nirvana after the suicide of Kurt Cobain.",
		id: "14",
		genre: "Rock",
		start: "20:00",
		bandName: "Foo Fighters",
	},
	{
		date: "26-03-2022",
		venue_id: 12,
		spotify: "https://open.spotify.com/artist/53KwLdlmrlCelAZMaLVZqU",
		end: "21:00",
		price: 16,
		description:
			"James Blake Litherland is an English singer, songwriter, multi-instrumentalist, and record producer. He first received recognition for a series of 2010 EPs including CMYK and Klavierwerke, and he released his self-titled debut album in 2011 to critical praise.",
		id: "72",
		genre: "Pop",
		start: "19:00",
		bandName: "James Blake",
	},
	{
		date: "27-03-2022",
		venue_id: 13,
		spotify: "https://open.spotify.com/artist/4uRYpUQZrNrY5t8tAv3XrD",
		end: "21:40",
		price: 16,
		description:
			"Nero are a British electronic music trio composed of members Dan Stephens, Joe Ray and Alana Watson. On 12 August 2011, they released their debut studio album, Welcome Reality, which reached number one in the UK Albums Chart. In August 2012, Promises received a Gold certification in the United States.",
		id: "73",
		genre: "Electronic",
		start: "19:40",
		bandName: "Nero",
	},
];
