exports.venueData = [
	{
		area: "Manchester",
		longitude: -2.23394,
		address: "31-33 Spear St, Manchester M1 1D",
		description:
			"A menu of seasonal soups, sandwiches, salads and mains, plus events including club/film nights.",
		id: "22",
		phone: "01236789456",
		latitude: 53.48314,
		name: "SOUP",
		opens: "12:00",
	},
	{
		area: "Manchester",
		longitude: -2.24405,
		address: "Hunts Bank, Manchester M3 1DA",
		description:
			"Integer mollis bibendum posuere. Nunc posuere vestibulum purus, maximus venenatis nunc ullamcorper finibus. Maecenas tristique lectus tellus, vel faucibus est efficitur sit amet. Praesent viverra urna erat, quis vulputate diam tincidunt sit amet. Quisque felis odio, finibus sit amet vehicula sed, pretium non odio.",
		id: "18",
		phone: "03331300967",
		latitude: 53.487049,
		name: "The Stoller Hall",
		opens: "11:00",
	},
	{
		area: "Manchester",
		longitude: -2.2395,
		address: "11 Bent St, Cheetham Hill, Manchester M8 8NF",
		description:
			"Nam non feugiat libero. Morbi pellentesque ligula ac dolor ornare ultricies. Donec interdum ut sapien placerat ornare. Nulla commodo neque sed volutpat suscipit.",
		id: "16",
		phone: "07768723724",
		latitude: 53.49565,
		name: "The Yard Manchester",
		opens: "12:00",
	},
	{
		area: "North West London",
		longitude: -0.15753,
		address: "Marylebone Rd, London NW1 5HT",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque massa orci, dictum id magna et, vulputate vehicula mauris. Integer eget nulla felis. Praesent dapibus volutpat porta. Vestibulum ullamcorper arcu ac enim suscipit efficitur. Vestibulum vulputate enim porttitor odio pulvinar consectetur. Maecenas vel velit in metus lobortis pharetra. Sed quis aliquam augue, vel efficitur tortor. Pellentesque dapibus egestas leo, vitae ultrices sapien.",
		id: "2",
		latitude: 51.52297,
		name: "The Duke's Hall",
		opens: "11:00",
		phone: "02078737373",
	},
	{
		area: "West London",
		longitude: -0.20255,
		address: "305 North End Rd, London W14 9NS",
		description:
			"Long-running gay venue hosting men-only nights & nights for TV/TS, gay men & their admirers.",
		id: "13",
		phone: "02073859359",
		latitude: 51.4858,
		name: "Ted's Place",
		opens: "17:00",
	},
	{
		area: "West London",
		longitude: -0.23167,
		address: "310 Uxbridge Rd, London W12 7LJ",
		description:
			"Bush Hall is located at 310 Uxbridge Road, Shepherd's Bush, West London, England. Originally a dance hall, it is now an independent music venue with a capacity of 400. Bush Hall was built in 1904.",
		id: "8",
		latitude: 51.50645,
		name: "Bush Hall",
		opens: "10:00",
		phone: "02082226955",
	},
	{
		area: "West London",
		longitude: -0.22278,
		address: "211 Shepherd's Bush Grn, London W12 8TT",
		description:
			"Shepherd's Bush Empire is a music venue in Shepherd's Bush, West London, run by the Academy Music Group. It was originally built in 1903 as a music hall for impresario Oswald Stoll, designed by theatre architect Frank Matcham; among its early performers was Charlie Chaplin.",
		id: "9",
		phone: "02083543300",
		latitude: 51.50322,
		name: "O2 Shepherd's Bush Empire",
		opens: "10:00",
	},
	{
		area: "North West London",
		longitude: -0.19879,
		address: "229 Kilburn High Rd, London NW6 7JG",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel ex eget eros mollis scelerisque. Ut porttitor rhoncus dolor, eu suscipit dolor. Pellentesque sit amet auctor mauris. Ut consequat non lacus sit amet facilisis. Etiam blandit at metus in accumsan. Aliquam magna lorem, suscipit at volutpat nec, iaculis cursus odio. Phasellus quis risus vehicula, placerat quam tincidunt, vehicula lorem. Sed efficitur nisl ut lacus posuere, sit amet pharetra elit vestibulum.",
		id: "1",
		latitude: 51.54234,
		name: "The Fiddler",
		opens: "17:00",
		phone: "01234567891",
	},
	{
		area: "South West London",
		longitude: -0.21057,
		address: "Fulham Rd, London SW6 1HS",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nibh erat, commodo quis quam sit amet, consectetur suscipit ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer lobortis arcu ac massa blandit, nec aliquet risus mattis. Maecenas ligula dolor, blandit vitae orci sed, lobortis tincidunt dui. Aenean sodales risus faucibus, aliquam augue ut, sodales ligula. In risus diam, rhoncus blandit lobortis sit amet, sollicitudin vitae sem. Phasellus at nulla porta, dapibus erat id, condimentum erat. Nunc vestibulum felis turpis, et lobortis nibh faucibus at. Morbi ut risus pretium, lobortis tortor nec, elementum felis. Integer efficitur condimentum fermentum. Quisque ultricies, neque sit amet facilisis venenatis, justo ante tincidunt quam, rhoncus accumsan ligula est quis nibh. Maecenas placerat tempor augue viverra hendrerit. In elementum, erat ac bibendum malesuada, urna est malesuada erat, ut efficitur ante ligula dignissim quam.",
		id: "6",
		latitude: 51.47155,
		name: "Under the Bridge",
		opens: "17:00",
		phone: "02079578261",
	},
	{
		area: "Manchester",
		longitude: -2.2482,
		address: "29 Jackson's Row, Manchester M2 5WD",
		description:
			"Donec ultrices mi eu ipsum imperdiet ultricies. In porta mauris quis lobortis aliquet. Duis vel augue cursus, malesuada sapien id, eleifend elit. Ut et pharetra massa.",
		id: "28",
		phone: "03336000186",
		latitude: 53.479061,
		name: "The Venue Nightclub",
		opens: "21:00",
	},
	{
		area: "Manchester",
		longitude: -2.24657,
		address: "54-56 Whitworth St, Manchester M1 5WW",
		description:
			"Industrial chic bar/club under the railway arches, with a grill menu, a gin parlour and live music.",
		id: "30",
		phone: "01614250870",
		latitude: 53.474018,
		name: "Gorilla",
		opens: "21:00",
	},
	{
		area: "Manchester",
		longitude: -2.23393,
		address: "109 Oldham St, Manchester M4 1LW",
		description:
			"Bar and live entertainment venue with a dance area plus a stage for shows and alternative concerts.",
		id: "24",
		phone: "01618192970",
		latitude: 53.48387,
		name: "Gullivers",
		opens: "12:00",
	},
	{
		area: "Manchester",
		longitude: -2.24923,
		address: "186 Deansgate, Manchester M3 3WB",
		description:
			"Donec ultrices mi eu ipsum imperdiet ultricies. In porta mauris quis lobortis aliquet. Duis vel augue cursus, malesuada sapien id, eleifend elit. Ut et pharetra massa.",
		id: "27",
		phone: "03336000186",
		latitude: 53.478889,
		name: "ONE EIGHT SIX",
		opens: "18:00",
	},
	{
		area: "North West London",
		longitude: -0.14586,
		address: "106 Parkway, London NW1 7AN",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus hendrerit tortor nec turpis gravida commodo. Nullam in suscipit lectus. Suspendisse suscipit cursus turpis, a tempus ex fermentum convallis. Sed non varius massa. Quisque eros neque, vulputate id erat consequat, varius posuere mi. Cras efficitur pharetra ligula non fermentum. Fusce ut dictum justo. Nam eget placerat quam, non posuere odio. Phasellus mauris eros, volutpat ut odio et, pellentesque tempus odio. Nulla facilisi. Quisque elementum pulvinar mauris at pharetra. Vivamus varius turpis in ultrices consectetur. Vestibulum porttitor velit eget velit congue, in fringilla arcu ullamcorper. Integer eget elit turpis. Integer pretium congue mi quis vehicula.",
		id: "5",
		latitude: 51.53726,
		name: "Green Note",
		opens: "19:00",
		phone: "02074859899",
	},
	{
		area: "North West London",
		longitude: -0.14922,
		address: "49 Chalk Farm Rd, Chalk Farm, London NW1 8AN",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sem risus, pulvinar nec pellentesque at, luctus eget mi. Cras placerat, ante ut scelerisque vehicula, augue dui interdum ligula, quis ullamcorper nisl magna sed dolor. Duis ut mi sit amet eros imperdiet accumsan at sit amet justo. Suspendisse sed quam ipsum. Maecenas vitae hendrerit justo. Donec a risus viverra, maximus ligula a, mattis leo. Nullam molestie nec est eget iaculis.",
		id: "4",
		latitude: 51.54311,
		name: "The Camden Assembly Pub",
		opens: "17:00",
		phone: "02074240800",
	},
	{
		area: "Manchester",
		longitude: -2.23381,
		address: "66 Oldham St, Manchester M4 1LE",
		description:
			"A pub with a long-standing reputation for live music and literary events, as well as its real ales.",
		id: "23",
		phone: "01612379485",
		latitude: 53.48381,
		name: "Castle Hotel",
		opens: "12:00",
	},
	{
		area: "Manchester",
		longitude: -2.23391,
		address: "27 Swan St, Manchester M4 5JZ",
		description:
			"Live music from rock to reggae and folk, with a cafe/bar and box office in a former cinema space.",
		id: "19",
		phone: "01618341786",
		latitude: 53.48522,
		name: "Band on the Wall",
		opens: "15:00",
	},
	{
		area: "Manchester",
		longitude: -2.25084,
		address: "13 Quay St, Manchester M3 3HN",
		description:
			"Nunc a consequat ligula, non maximus tortor. Vivamus ornare, leo quis dictum accumsan, arcu felis tincidunt ligula, a aliquet diam dui id nibh. Ut convallis orci leo, et placerat ante accumsan quis. Suspendisse pellentesque varius tortor nec iaculis. Suspendisse eu facilisis ante. Phasellus lorem magna, pretium sed dapibus non, mollis at neque. Aliquam porttitor pretium justo. Ut eu tellus diam. Sed euismod neque a enim consectetur, porta tristique dolor efficitur. Ut fringilla elit non porta luctus. In molestie ipsum sit amet blandit lacinia. Sed non orci ut odio vehicula dignissim non id ipsum. Praesent congue, erat eu maximus ultrices, massa mauris facilisis massa, ut fermentum justo odio sed tellus.",
		id: "26",
		phone: "01618236343",
		latitude: 53.47848,
		name: "The Blues Kitchen",
		opens: "13:00",
	},
	{
		area: "West London",
		longitude: -0.20761,
		address: "3 North End Crescent, London W14 8TG",
		description:
			"Sed at ultrices mauris. Etiam et aliquet nibh. Fusce venenatis felis eu viverra accumsan. Vivamus semper, metus in ornare euismod, dui elit vehicula ex, in mollis odio purus et diam. Integer id mattis neque. Sed in orci id tellus euismod lobortis. Aliquam nec nulla consectetur, accumsan quam a, dictum velit. Praesent vel luctus leo. Fusce consectetur ligula odio, id faucibus lorem euismod eget. Praesent tincidunt gravida blandit. Aenean dapibus porta arcu ac semper. Cras posuere nulla nec dolor aliquet, in mollis augue semper. Vivamus nulla elit, malesuada at turpis accumsan, laoreet iaculis arcu.",
		id: "7",
		latitude: 51.4928,
		name: "Nell's",
		opens: "17:00",
		phone: "02345678912",
	},
	{
		area: "West London",
		longitude: -0.22559,
		address: "81 King St, London W6 9HW",
		description:
			"Regular folk and acoustic gigs in cosy wood panelled pub with large windows and streetside seating.",
		id: "11",
		phone: "02087484511",
		latitude: 51.49307,
		name: "The Hammersmith Ram",
		opens: "18:00",
	},
	{
		area: "North West London",
		longitude: -0.14218,
		address: "174 Camden High St, London NW1 0NE",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ipsum leo, pellentesque eu gravida iaculis, lobortis eu augue. In et erat ac lorem accumsan fringilla pharetra vitae mauris. Donec ac congue massa, vel maximus enim. Nunc suscipit velit neque, eu elementum dolor pharetra ut. Praesent mollis nisi leo, in venenatis ipsum fermentum nec. Pellentesque lobortis leo eu lacus imperdiet, sed dignissim nisl porttitor. Nulla velit nulla, aliquet nec dapibus nec, tincidunt id erat.",
		id: "3",
		latitude: 51.53914,
		name: "The Underworld",
		opens: "18:00",
		phone: "02072673939",
	},
	{
		area: "Manchester",
		longitude: -2.24601,
		address: "St Ann's Square, Manchester M2 7DH",
		description:
			"Manchester's former cotton exchange stages events in the round in architecturally stunning space.",
		id: "20",
		phone: "01618339833",
		latitude: 53.48271,
		name: "Royal Exchange Theatre",
		opens: "14:00",
	},
	{
		area: "Manchester",
		longitude: -2.2398,
		address: "118 Princess St, Manchester M1 7EN",
		description:
			"Quisque molestie sapien id aliquam varius. Sed ut tellus magna. Mauris vestibulum fermentum ante id mollis. Curabitur lacinia laoreet pellentesque. Praesent eget mattis urna. Sed nisl erat, sagittis et blandit facilisis, dapibus at tellus.",
		id: "29",
		phone: "01616372570",
		latitude: 53.477211,
		name: "FAC251 - Factory Manchester",
		opens: "21:00",
	},
	{
		area: "Manchester",
		longitude: -2.23377,
		address: "11 Stevenson Square, Manchester M1 1DB",
		description:
			"Cras dignissim orci sed justo fringilla, at euismod sem mollis. Aenean luctus laoreet ex, sodales tempor nisl iaculis a. Nunc at aliquet lacus. Sed ut orci rhoncus, semper massa vitae, egestas lectus. Phasellus sagittis laoreet libero eu tincidunt. In vitae mauris ultricies, mattis justo id, pulvinar diam.",
		id: "21",
		phone: "01614083626",
		latitude: 53.482571,
		name: "Kraak",
		opens: "16:00",
	},
	{
		area: "Manchester",
		longitude: -2.24795,
		address: "City Centre, 27 Peter St, Manchester M2 5QR",
		description:
			"The Albert Hall is a music venue in Manchester, England. Built as a Methodist central hall in 1908 by the architect William James Morley of Bradford and built by J. Gerrard & Sons Ltd of Swinton, it has been designated by English Heritage as a Grade II listed building.",
		id: "25",
		phone: "01618173490",
		latitude: 53.478142,
		name: "Albert Hall",
		opens: "12:00",
	},
	{
		area: "South West London",
		longitude: -0.19941,
		address: "374 North End Rd, London SW6 1LY",
		description:
			"Cocktail bar with retro wallpaper serving shareable drinks, beer & wine, with a long happy hour.",
		id: "12",
		phone: "02038799248",
		latitude: 51.48106,
		name: "Simmons Bar",
		opens: "16:00",
	},
	{
		area: "Manchester",
		longitude: -2.24911,
		address: "16-18 Mary St, Cheetham Hill, Manchester M3 1NH",
		description:
			"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed auctor metus quis tortor porttitor, ac semper quam malesuada. Nunc sodales turpis pulvinar hendrerit dignissim.",
		id: "17",
		phone: "02345577669",
		latitude: 53.490082,
		name: "Hidden at Downtex Mill",
		opens: "11:00",
	},
	{
		area: "West London",
		longitude: -0.22782,
		address: "45 Queen Caroline St, London W6 9QH",
		description:
			"The Hammersmith Apollo, currently called the Eventim Apollo for sponsorship reasons, but formerly – and still commonly – known as the Hammersmith Odeon, is a live entertainment performance venue, originally built as a cinema, located in Hammersmith, London. It is an art deco Grade II* listed building.",
		id: "10",
		phone: "02085633800",
		latitude: 51.49016,
		name: "Eventim Apollo",
		opens: "18:00",
	},
	{
		area: "North West London",
		longitude: -0.13859,
		address: "2A Dartmouth Park Hill, London NW5 1HL",
		description:
			"Gig venue above a pub, hosting a range of live bands, club nights and other music events.",
		id: "15",
		phone: "02081038951",
		latitude: 51.557152,
		name: "The Dome",
		opens: "17:00",
	},
	{
		area: "South West London",
		longitude: -0.19161,
		address: "265-267 Old Brompton Rd, London SW5 9JA",
		description:
			"In dignissim, ligula et aliquet accumsan, ex mauris pharetra quam, quis mattis neque dolor nec lectus. Sed vel hendrerit elit. Etiam et feugiat mi. Integer ut egestas felis. Ut tristique, metus pellentesque faucibus sollicitudin, nunc eros vulputate lacus, sed semper urna quam vitae urna. Integer ornare eleifend arcu, vel lacinia ligula fermentum et. Proin sit amet nibh commodo, semper urna in, rhoncus ligula. Integer auctor ipsum eget augue fringilla aliquet. Mauris vitae eleifend nulla. Donec tincidunt nec arcu quis porta. Pellentesque diam ex, ullamcorper id dui id, vehicula vehicula dolor.",
		id: "14",
		phone: "02073416333",
		latitude: 51.48883,
		name: "The Troubadour",
		opens: "09:00",
	},
];
